#Yonatan

#server:
 #      port: 8761



#eureka:
#       client:
 #              fetch-registry: false
 #              register-with-eureka : false




server :
        port : 8761


eureka:
    client:
           fetch-registry : false 

           register-with-eureka: false